### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by bendisposto** [ProPra16/programmierpraktikum-abschlussprojekt-team-mannschaft#10]
Ihr habt Build-Fehler in Travis. Das liegt ziemlich sicher an der Java Version in Travis, es gibt dazu eine Diskussion im Ilias (Thema: Travis Java version "1.8.0_31")

**Comment by haftbefehl** [comment]
Das Hinzufügen des Codes aus Ilias bringt nichts. Das war ja auch die ganze Zeit schon drin. Laut http://lint.travis-ci.org/ , eine Seite zum Überprüfen der travis.yml kommen auch diese Fehler beim Hinzufügen dieses Codes raus:    
    unexpected key apt, dropping
    unexpected key packages, dropping
    value for addons section is empty, dropping

Ich glaube deshalb, dass Travis vielleicht die Klasse Spinner einfach nicht kennt.

**Comment by haftbefehl** [comment]
Vielleicht gibt es auch eine andere Lösung, diese ist aber nicht in Ilias zu finden und auch im Internet hab ich nach langer Suche nichts gefunden.

**Comment by haftbefehl** [comment]
Es ist vielleicht anzumerken, dass das Programm nur mit gradle, also ohne Travis ganz normal gebuildet und auch ausgeführt werden kann. Travis nutzt vielleicht eine alte Gradle version, ich weiß jedenfalls nicht was man tun könnte, zumal Gradle Spinner und alle anderen Klassen kennt.

**Comment by bendisposto** [comment]
Die Ausgaben von Travis haben gezeigt, das Java 1.8.0_31 benutzt wurde (Mache Dinge wie Spinner oder Alert sind erst später in Java hinzugekommen). Es hatte nichts mit Travis zu tun, das baut nur eine virtuelle Maschine und kompiliert den Code. Insofern kennt es kein Klassen. Mit Travis kann man auch Ruby oder Python Programme bauen.

Der Fehler war, das die Syntax falsch war (das hat auch der linter versucht mitzuteilen). Die Einrückung ist bei der Skriptpsrache relevant.

Ich habe das repariert, es gibt aber noch einen Fehler wegen eines Sonderzeichens. Behebt das bitte noch.

**Comment by haftbefehl** [comment]
Erstmal vielen Dank für das Beheben des Fehlers. Nun scheint travis das Programm builden zu können allerdings beendet es den Vorgang nicht, sondern es wartet nach dem Durchlaufen der Build Schritte 10 Minuten woraufhin es zu einem Timeout kommt, da travis diese 10 Minuten kein Output rausbekommt. Ich weiß jetzt wiederum nicht womit das zusammenhängt.

**Comment by bendisposto** [comment]
Eure Tests terminieren nicht, wenn man kein Display ansprechen kann. Ich habe das Debugging bei Gradle angeschaltet und auf Travis gibt es eine Exception.

17:28:54.847 [QUIET] [system.out] 17:28:54.846 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class test.java.TimerTest
17:28:54.850 [DEBUG] [TestEventLogger] 
17:28:54.850 [DEBUG] [TestEventLogger] test.java.TimerTest STARTED
17:28:54.853 [DEBUG] [TestEventLogger] 
17:28:54.854 [DEBUG] [TestEventLogger] test.java.TimerTest > thirdTest STARTED
17:28:55.723 [DEBUG] [TestEventLogger] 
17:28:55.726 [DEBUG] [TestEventLogger] test.java.TimerTest > thirdTest STANDARD_ERROR
17:28:55.727 [DEBUG] [TestEventLogger]     Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Unable to open DISPLAY
17:28:55.727 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)

**Comment by Joshua27** [comment]
Wenn Hamcrest zu den Libraries im Build-Path hinzugefügt wird gehen die Tests durch.

**Comment by Joshua27** [comment]
Auf Travis geht TimerTest nicht durch, da man kein Display ansprechen kann wie Jens bereits richtig angemerkt hat. Lokal funktionieren die Tests. Ist jetzt auskommentiert und der Build ist erfolgreich.
