### ISSUE TITLE
Timer: REFACTOR-Phase

### ISSUE THREAD

**Issue by Joshua27** [ProPra16/programmierpraktikum-abschlussprojekt-team-mannschaft#9]
In der REFACTOR-Phase wird die Zeitlimitierung angezeigt, obwohl es in dieser Phase eigentlich keine geben sollte. Wenn diese bei 0 ist passiert zwar nichts und die Zeit läuft erneut ab, aber das macht ja wenig Sinn. Hier sollte der Timer nicht im Hintergrund laufen und die Zeit auch nicht angezeigt werden.
Man könnte vielleicht einen normalen Timer bei 0 startend anzeigen, um zu sehen wie lange man bereits in dieser Phase ist. 
@PhilippStumpe @TKay1995 @ sameh

**Comment by RoterEmu** [comment]
Bitte die E-Mails immer an alle schicken!

**Comment by RoterEmu** [comment]
Bei diesem "Fehler" handelt es sich um eine Änderung von einer halben Zeile im Code vom Renato .. der hat das schnell angepasst!

**Comment by Joshua27** [comment]
Da du aber schon mehr als genug für das Projekt getan hast, möchte ich im besten Fall, dass jemand anderes das Problem erledigt.

**Comment by Joshua27** [comment]
Na gut, habe ich mir schon fast gedacht. Der Thread musste halt einfach geschlossen werden.
Wenn das Problem erledigt ist, bitte den Issue schließen.
